inherit_gem:
  rubocop-mhenrixon:
    - config/default.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'gemfiles/**/*'
    - '**/*.json'

Naming/VariableNumber:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false